export {default as Article} from './article/Article'
export {default as Partners} from './partners/Partners'
export {default as CTA} from './cta/CTA'
export {default as Feature} from './feature/Feature'
export {default as Navbar} from './navbar/Navbar'
