name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Docker
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Build and Push Docker Image
        run: |
          docker login --username ${{github.actor}} --password ${{secrets.GH_PAT}} ghcr.io
          docker build -t ghcr.io/aleksandargazikalovic/wheeldeal:latest -f Dockerfile.frontend .
          docker push ghcr.io/aleksandargazikalovic/wheeldeal:latest

      - name: Deploy to DigitalOcean Droplet
        uses: appleboy/ssh-action@v1.0.1
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          port: 22
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_PAT }}
            docker pull ${{secrets.DOCKER_IMAGE}}
            docker run -d -p 8080:80 --name your-container ${{secrets.DOCKER_IMAGE}}
